// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

package proto

import (
	context "context"
	fmt "fmt"
	micro "github.com/fananchong/protoc-gen-vmicro/micro"
	client "github.com/fananchong/v-micro/client"
	server "github.com/fananchong/v-micro/server"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ micro.NoReply

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*Response)(nil), "proto.Response")
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor_e585294ab3f34af5) }

var fileDescriptor_e585294ab3f34af5 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2f, 0x4a, 0x4d,
	0x2d, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0xa2, 0xb9,
	0x99, 0xc9, 0x45, 0xf9, 0xfa, 0x49, 0x45, 0xf9, 0x89, 0x29, 0xc9, 0x89, 0xc5, 0x25, 0x10, 0x59,
	0x25, 0x59, 0x2e, 0xf6, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0xbc,
	0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x49, 0x86, 0x8b, 0x23,
	0x28, 0xb5, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x80, 0x8b, 0x39, 0xb7, 0x38, 0x1d, 0x2a,
	0x0d, 0x62, 0x1a, 0xc5, 0x73, 0x31, 0x07, 0x27, 0x56, 0x0a, 0xe9, 0x72, 0xb1, 0x7a, 0xa4, 0xe6,
	0xe4, 0xe4, 0x0b, 0xf1, 0x41, 0x0c, 0xd5, 0x83, 0x9a, 0x28, 0xc5, 0xa7, 0x07, 0xb6, 0x54, 0xcf,
	0x2f, 0x3f, 0x28, 0xb5, 0x20, 0xa7, 0x52, 0x89, 0xa5, 0x61, 0xab, 0x04, 0xa3, 0x90, 0x26, 0x17,
	0x4b, 0x40, 0x66, 0x5e, 0x3a, 0x86, 0x6a, 0x7e, 0x38, 0x1f, 0x62, 0xa1, 0x12, 0x43, 0x12, 0x1b,
	0x58, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x75, 0xe2, 0x29, 0xfd, 0xd3, 0x00, 0x00, 0x00,
}

// Client API for Say service

type SayService interface {
	BroadcastHello(ctx context.Context, req *Request, opts ...client.CallOption)
	Ping(ctx context.Context, req *Request, opts ...client.CallOption) error
}

type SayCallback interface {
	Ping(ctx context.Context, req *Request, rsp *Response)
}

type sayService struct {
	c    client.Client
	name string
}

func NewSayService(name string, hdcb SayCallback, c client.Client) SayService {
	if c == nil {
		panic("client is nil")
	}
	if len(name) == 0 {
		panic("name is nil")
	}
	if err := c.Handle(hdcb); err != nil {
		panic(err)
	}
	return &sayService{
		c:    c,
		name: name,
	}
}

func (c *sayService) BroadcastHello(ctx context.Context, req *Request, opts ...client.CallOption) {
	r := c.c.NewRequest(c.name, "Say.BroadcastHello", req)
	c.c.Broadcast(ctx, r, opts...)
}

func (c *sayService) Ping(ctx context.Context, req *Request, opts ...client.CallOption) error {
	r := c.c.NewRequest(c.name, "Say.Ping", req)
	err := c.c.Call(ctx, r, opts...)
	if err != nil {
		return err
	}
	return nil
}

// Server API for Say service

type SayHandler interface {
	BroadcastHello(ctx context.Context, req *Request, rsp *micro.NoReply) error
	Ping(ctx context.Context, req *Request, rsp *Response) error
}

func RegisterSayHandler(s server.Server, hdlr SayHandler) error {
	return s.Handle(hdlr)
}
