language: go

go:
  - 1.12.x

before_script:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin

env:
  - GO111MODULE=on GOPROXY=https://goproxy.io

script:
  - golangci-lint run
  - ./make.sh build
  - ./make.sh coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)