// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

package proto

import (
	context "context"
	fmt "fmt"
	micro "github.com/fananchong/protoc-gen-vmicro/micro"
	client "github.com/fananchong/v-micro/client"
	server "github.com/fananchong/v-micro/server"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_e585294ab3f34af5, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "proto.Request")
}

func init() { proto.RegisterFile("greeter.proto", fileDescriptor_e585294ab3f34af5) }

var fileDescriptor_e585294ab3f34af5 = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2f, 0x4a, 0x4d,
	0x2d, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0xa2, 0xb9,
	0x99, 0xc9, 0x45, 0xf9, 0xfa, 0x49, 0x45, 0xf9, 0x89, 0x29, 0xc9, 0x89, 0xc5, 0x25, 0x10, 0x59,
	0x25, 0x59, 0x2e, 0xf6, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0xbc,
	0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0xdb, 0x28, 0x8e, 0x8b, 0x39,
	0x38, 0xb1, 0x52, 0x48, 0x97, 0x8b, 0xd5, 0x23, 0x35, 0x27, 0x27, 0x5f, 0x88, 0x0f, 0xa2, 0x4d,
	0x0f, 0xaa, 0x47, 0x8a, 0x4f, 0x0f, 0x6c, 0xac, 0x9e, 0x5f, 0x7e, 0x50, 0x6a, 0x41, 0x4e, 0xa5,
	0x12, 0x4b, 0xc3, 0x56, 0x09, 0x46, 0x21, 0x0d, 0x2e, 0x96, 0x80, 0xcc, 0xbc, 0x74, 0x82, 0xaa,
	0x19, 0x92, 0xd8, 0xc0, 0x0a, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x64, 0xad, 0xd5, 0xa7,
	0xb4, 0x00, 0x00, 0x00,
}

// Client API for Say service

type SayService interface {
	Hello(ctx context.Context, req *Request, opts ...client.CallOption) error
	Ping(ctx context.Context, req *Request, opts ...client.CallOption) error
}

type SayCallback interface {
	Hello(ctx context.Context, req *Request, rsp *micro.NoReply)
	Ping(ctx context.Context, req *Request, rsp *micro.NoReply)
}

type sayService struct {
	c    client.Client
	name string
}

func NewSayService(name string, hdcb SayCallback, c client.Client) SayService {
	if c == nil {
		panic("client is nil")
	}
	if len(name) == 0 {
		panic("name is nil")
	}
	if err := c.Handle(hdcb); err != nil {
		panic(err)
	}
	return &sayService{
		c:    c,
		name: name,
	}
}

func (c *sayService) Hello(ctx context.Context, req *Request, opts ...client.CallOption) error {
	r := c.c.NewRequest(c.name, "Say.Hello", req)
	err := c.c.Call(ctx, r, opts...)
	if err != nil {
		return err
	}
	return nil
}

func (c *sayService) Ping(ctx context.Context, req *Request, opts ...client.CallOption) error {
	r := c.c.NewRequest(c.name, "Say.Ping", req)
	err := c.c.Call(ctx, r, opts...)
	if err != nil {
		return err
	}
	return nil
}

// Server API for Say service

type SayHandler interface {
	Hello(ctx context.Context, req *Request, rsp *micro.NoReply) error
	Ping(ctx context.Context, req *Request, rsp *micro.NoReply) error
}

func RegisterSayHandler(s server.Server, hdlr SayHandler) error {
	return s.Handle(hdlr)
}
